# Activate with --spring.profiles.active=postgres (in addition to auth/rs)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=dbuser
spring.datasource.password=12345
