CREATE TABLE IF NOT EXISTS users (
    user_id       VARCHAR(64)  PRIMARY KEY,
    username      VARCHAR(128) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    BIGINT       NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS roles (
    role_name   VARCHAR(64) PRIMARY KEY,
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS role_scopes (
    role_name VARCHAR(64)  NOT NULL,
    scope     VARCHAR(128) NOT NULL,
    PRIMARY KEY (role_name, scope)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id   VARCHAR(64) NOT NULL,
    role_name VARCHAR(64) NOT NULL,
    PRIMARY KEY (user_id, role_name)
);

CREATE TABLE IF NOT EXISTS clients (
    client_id          VARCHAR(64)  PRIMARY KEY,
    client_secret_hash VARCHAR(100) NOT NULL,
    audience           VARCHAR(128) NOT NULL,
    enabled            BOOLEAN      NOT NULL DEFAULT TRUE,
    description        VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS client_grants (
    client_id  VARCHAR(64) NOT NULL,
    grant_type VARCHAR(32) NOT NULL,
    PRIMARY KEY (client_id, grant_type)
);

CREATE TABLE IF NOT EXISTS client_scopes (
    client_id VARCHAR(64)  NOT NULL,
    scope     VARCHAR(128) NOT NULL,
    PRIMARY KEY (client_id, scope)
);

-- one row per issued refresh token; "rotated" marks a token that was already exchanged
CREATE TABLE IF NOT EXISTS refresh_index (
    refresh_id  VARCHAR(64)   PRIMARY KEY,
    user_id     VARCHAR(64),
    client_id   VARCHAR(64)   NOT NULL,
    scopes      VARCHAR(1024) NOT NULL,
    issued_at   BIGINT        NOT NULL,
    expires_at  BIGINT        NOT NULL,
    rotated     BOOLEAN       NOT NULL DEFAULT FALSE,
    revoked     BOOLEAN       NOT NULL DEFAULT FALSE,
    replaced_by VARCHAR(64)
);

-- revocation journal: token_type = 'access' (token_ref = jti) or 'refresh' (token_ref = refresh_id)
CREATE TABLE IF NOT EXISTS revocation (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_type VARCHAR(16) NOT NULL,
    token_ref  VARCHAR(64) NOT NULL,
    expires_at BIGINT      NOT NULL,
    revoked_at BIGINT      NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_revocation_ref ON revocation (token_type, token_ref);

-- audit / metrics: one row per event, never contains secrets
CREATE TABLE IF NOT EXISTS audit_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(64) NOT NULL,
    outcome    VARCHAR(16) NOT NULL,
    client_id  VARCHAR(64),
    user_id    VARCHAR(64),
    details    VARCHAR(512),
    created_at BIGINT      NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_events (created_at);
